[UIPO-1] Project skeleton
Nazar-bnm/ui-internship pull request #1
Opened 2019-09-25 10:33 UTC by TorskyM

2019-09-25 11:19 UTC, Nazar-bnm requested changes

2019-09-25 11:19 UTC, Nazar-bnm commented on README.md
> +Type next command in Terminal: ```install node```
Is it works ?

2019-09-25 11:19 UTC, Nazar-bnm commented on README.md
> +You will need to use a Terminal.
Please add which version of the node we should use and how we can check it

2019-09-25 11:19 UTC, Nazar-bnm commented on README.md
> +```npm run scss``` - start node-sass compiler
why should we run the `scss` compiler? It should works automatically.

2019-09-25 11:19 UTC, Nazar-bnm commented on dist/index.html
> +<!DOCTYPE html>
dist ащдвук should be ignored by git

2019-09-25 11:19 UTC, Nazar-bnm commented on package.json
> +  "description": "My webpack project",
Please change name and description to  more suitable

2019-09-25 11:19 UTC, Nazar-bnm commented on src/app/index.js
> +console.log("Hello World");
Where do you connect React to the project?

2019-09-25 11:45 UTC, Hollister009 commented on package.json
> +    "eslint-config-standard-jsx": "^8.1.0",
Shouldn't it be in `devDependencies`?

2019-09-26 06:53 UTC, Hollister009 commented on package.json
> +    "node": ">=12.0.0",
I'm not sure about this versioning 🤔maybe `"node": ">=10.x"`

2019-09-26 06:55 UTC, Hollister009 commented on src/app/components/app.js
> +/* eslint-disable require-jsdoc */
remove this comments

2019-09-26 06:55 UTC, Hollister009 commented on src/app/components/app.js
> +
Please remove unnecessary comments

2019-09-26 06:57 UTC, Hollister009 commented on src/app/scss/main.scss
> +}
Delete test styles

2019-09-26 06:57 UTC, Hollister009 commented on src/app/index.js
> +import {Provider} from 'react-redux';
Why this change even here?

2019-09-26 06:59 UTC, Hollister009 commented on src/app/components/app.js
>  export default App;
I believe this file should be not included inchnages

2019-09-26 07:02 UTC, Hollister009 requested changes
Needs a little cleanup. Remove `app.js` and `main.scss` from PR

2019-09-26 15:24 UTC, Sviatoslav-Paliichuk approved these changes

2019-09-26 15:27 UTC, merged