[UIPO-38] brands and shipping info
Nazar-bnm/ui-internship pull request #34
Opened 2019-10-10 15:40 UTC by olenakachmar

2019-10-10 19:30 UTC, Hollister009 commented on src/components/Brands/Brands.scss
> +      &-item {
can be simplified on 1 level

2019-10-10 19:32 UTC, Hollister009 commented on src/components/Brands/Brands.spec.js
> +const mockData = [
can you put this mockData for reusability into a separate file

2019-10-10 19:34 UTC, Hollister009 commented on src/components/ShippingInfo/ShippingInfo.js
> +const { shippingData } = config;
hmm, this import should be on line 4

2019-10-10 19:36 UTC, Hollister009 commented on src/components/ShippingInfo/ShippingInfo.spec.js
> +  });
Better just test if it matches snapshot

2019-10-10 19:38 UTC, Hollister009 reviewed
Overall, nice job!

2019-10-11 14:01 UTC, Nazar-bnm requested changes

2019-10-11 14:01 UTC, Nazar-bnm commented on src/components/Brands/Brands.js
> +      </li>
move it to class method, for example renderBrendes() {}

2019-10-11 14:01 UTC, Nazar-bnm commented on src/components/ShippingInfo/ShippingInfo.js
> +    </li>
add object destruction for elem

2019-10-11 14:32 UTC, Nazar-bnm approved these changes

2019-10-11 14:32 UTC, merged