Product order and image integration
Nazar-bnm/ui-internship pull request #40
Opened 2019-10-20 14:44 UTC by myrosvas

Two components: [product order](https://prnt.sc/pltxu9) and [product image](https://prnt.sc/pltxms) have been integrated into PDP.

2019-10-21 18:03 UTC, Hollister009 commented
@KhrystynaVaskovych can you review this one for me?

2019-10-21 19:48 UTC, KhrystynaVaskovych commented
@Hollister009 , sure!

2019-10-21 20:12 UTC, KhrystynaVaskovych requested changes
Well done! :) Needs miiiinor corrections)

2019-10-21 20:12 UTC, KhrystynaVaskovych commented on src/components/Button/Button.js
> +import './Button.scss';
empty line would be great before scss import :)

2019-10-21 20:12 UTC, KhrystynaVaskovych commented on src/components/ProductDetailsPage/ProductDetailsPage.js
> +    <ProductImage imagesArr={defaultImages} />
it's good to name variables without 'Arr'

2019-10-21 20:12 UTC, KhrystynaVaskovych commented on src/components/ProductDetailsPage/ProductDetailsPage.scss
> +@import "../../scss/global_styles";
import with single quotes)

2019-10-21 20:12 UTC, KhrystynaVaskovych commented on src/components/ProductImage/ProductImage.js
>      const { imagesArr } = this.props;
same here^ would be better without 'Arr'

2019-10-21 20:12 UTC, KhrystynaVaskovych commented on src/components/ProductImage/ProductImage.scss
>  @import "../../scss/global_styles";
trouble with quotes, should be single

2019-10-21 20:12 UTC, KhrystynaVaskovych commented on src/components/ProductImage/ProductImage.scss
> +    background-color: rgba(244, 162, 54, 0.7);
would be good to create a variable:)

2019-10-21 20:12 UTC, KhrystynaVaskovych commented on src/components/ProductImage/ProductImage.scss
> +    border: 2px solid rgba(244, 162, 54, 1);;
same here, be so kind to add to variables, perhaps we'll need it)

2019-10-21 20:12 UTC, KhrystynaVaskovych commented on src/components/Button/Button.scss
> +@import "../../scss/global_styles";
please, change to single quotes:)

2019-10-21 20:12 UTC, KhrystynaVaskovych commented on src/components/ProductDetailsPage/ProductDetailsPageContainer.js
> +        <div>{productName}</div>
why div?

2019-10-22 13:10 UTC, Nazar-bnm approved these changes

2019-10-22 13:10 UTC, merged