[UIPO-54] Make Carousel work vertical
Nazar-bnm/ui-internship pull request #66
Opened 2019-11-07 10:38 UTC by KhrystynaKovtun

I also added Carousel to Product Image, styled Carousel in Quick view, styled Product Details, fixed some warnings.

2019-11-07 11:00 UTC, nadiiaLebedenko requested changes

2019-11-07 11:00 UTC, nadiiaLebedenko commented on src/components/Accordion/Accordion.js
> +    return array.map((element) => ({ isHidden: !open, ...element }));
Are you sure element.isHidden won't overwrite new value?

2019-11-07 11:00 UTC, nadiiaLebedenko commented on src/components/ProductDetailsPage/ProductDetailsPage.js
> +      <>
This shoudn't be here

2019-11-07 11:00 UTC, nadiiaLebedenko commented on src/components/ProductDetailsPage/ProductDetailsPage.js
> +      Go Back
Please, fix indents

2019-11-07 16:19 UTC, KhrystynaKovtun commented on src/components/Accordion/Accordion.js
> +    return array.map((element) => ({ isHidden: !open, ...element }));
That is why I did it.  if in data is present isHidden I want to set to that value, not a default one)

2019-11-07 16:34 UTC, KhrystynaKovtun commented on src/components/ProductDetailsPage/ProductDetailsPage.js
> +      <>
Why?

2019-11-08 10:59 UTC, nadiiaLebedenko approved these changes

2019-11-08 10:59 UTC, merged