[UIPO-79] What's new: add hover on images
Nazar-bnm/ui-internship pull request #85
Opened 2019-11-18 09:49 UTC by KhrystynaKovtun

2019-11-18 16:08 UTC, Nazar-bnm requested changes

2019-11-18 16:08 UTC, Nazar-bnm commented on src/components/WhatIsNew/ItemInfo/__snapshots__/ItemInfo.spec.js.snap
> +  className="col-4 item "
remove extra space

2019-11-18 16:08 UTC, Nazar-bnm commented on src/components/WhatIsNew/WhatIsNew.js
> +      <ItemInfo className="whatIsNew-wrapper__item" key={item.id} item={item} />
why do u use camelcase for class selector ?

2019-11-25 10:40 UTC, ghost approved these changes

2019-11-25 13:18 UTC, Hollister009 approved these changes

2019-11-25 13:21 UTC, merged